### ISSUE TITLE
Message Sending Activity graph

### ISSUE THREAD

**Issue by MathiasSven** [bsnk-dev/bar3-client#3]
For non-americans if you run the server the dates are stored in dd/mm/yyyy however the graph still tries to display it in mm/dd/yyyy. So as you can see below, test messages were sent on the 3rd, 5th, and 6th of July but it is showing as if the days represented different months.

![Screenshot 2021-07-06 032314](https://user-images.githubusercontent.com/24759037/124552159-8a391200-de09-11eb-888d-ebe760b31618.png)

**Comment by bsnk-dev** [comment]
Thanks for bringing this to my attention. The graph is trying to decode the time as mm/dd/yyyy even when handed local time. I'll have this fixed soon.

**Comment by bsnk-dev** [comment]
fixed in af1af2840e2eada1733ab9793d7a2796e76df3d6 -- will get put into Bar 3 in the next release
